dist: bionic
language: php
sudo: false

#php:
#  - "7.2"
#  - "7.4"
#  - "8.1"

env:
  global:
    - SYMFONY_PHPUNIT_DIR=$HOME/.symfony-phpunit

matrix:
  fast_finish: true
  include:
    - php: "7.2"
    - php: "7.4"
    - php: "8.1"
      env: XDEBUG_MODE=coverage

before-install:
  - composer --no-interaction self-update
  - composer --no-interaction config --list

before_script:
  - composer --no-interaction config platform.php $TRAVIS_PHP_VERSION
  #- composer config platform.php <version-name>
  - composer --no-interaction update
  #- phpenv version-name | grep ^5.[34] && echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; true
  #- phpenv version-name | grep ^5.[34] && echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; true

script:
  - mkdir -p build/logs
  - phpunit --testdox-text --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - travis_retry php vendor/bin/php-coveralls

cache:
  directories:
    - vendor
    - $HOME/.symfony-phpunit
    - $HOME/.composer/cache/files

git:
  depth: 5

notifications:
  email:
    - "nick.lavrik@gmail.com"
